source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-assets', '~> 2.4.0'
gem 'jekyll-timeago'
gem 'jekyll-seo-tag'
gem 'haml'
gem 'rouge', git: 'https://github.com/manastech/rouge.git', branch: 'crystal'
gem 'html-proofer'
gem 'kramdown-parser-gfm'
