#############################  Cache  ###############################

# Enable link caching. This can be helpful to avoid checking the same links on
# multiple runs.
cache = true

# Discard all cached requests older than this duration.
max_cache_age = "7d"

#############################  Requests  ############################

exclude_path = [
  "_site",                             # build output
  "_sass/mixins/_link-with-icon.scss", # lists URL prefixes,
  "_data/packages.yaml",               # contains URL templates
  "_data/packages-nightly.yaml",       # contains URL templates

  # contains templates with incomplete URLs
  "_plugins",
  "_layouts",
  "_includes",
  "_style_guide",
  "_pages/blog/authors.html",
  "_pages/blog/tags.html",
  "_pages/sitemap.html",
  "index.md",
]

# Enable the checking of fragments in links.
include_fragments = true

# Root path to use when checking absolute local links, must be an absolute path
root_dir = "."

#############################  Exclusions  ##########################

exclude = [
  "^https?://(www\\.)?linkedin\\.com/",                      # all requests result in 999
  "^https?://(www\\.)?medium\\.com/",                        # all requests result in 403
  "^https?://(www\\.)?reddit\\.com/",                        # all requests result in 403
  "^https?://(www\\.)?youtube\\.com/",                       # all requests result in 404
  "^https?://0\\.0\\.0\\.0:",                                # local development server
  "^https?://cdn\\.pbrd\\.co/",                              # all requests result in 403
  "^https?://github\\.com/crystal-lang/crystal/stargazers$", # only available to logged-in users
  "^https?://software\\.opensuse\\.org/",                    # all requests result in 400
  "^https?://t\\.co/",                                       # all requests result in 400
  "^https?://twitter\\.com/",                                # all requests result in 400
  "^https?://us6\\.campaign-archive\\.com/",                 # all requests result in 404

  # Fragment links that are not valid URLs
  "^https?://app\\.gitter\\.im/#/room/#crystal-lang_crystal:gitter\\.im$",
  "^https?://github\\.com/.*#issuecomment-.*$",
  "^https?://github\\.com/.*#L[0-9]+(-L[0-9]+)?$",
  "^https?://matrix\\.to/#/#crystal-lang_crystal:gitter\\.im$",
  "^https?://play\\.crystal-lang\\.org/#/",
  "^https?://web\\.libera\\.chat/#crystal-lang$",
  "^https?://www\\.techempower\\.com/benchmarks/#section=data-r15&test=plaintext",

  # Skip archive.org links to avoid unnecessary requests.
  # Archive links should usually exists, but requests are heavy.
  "^https?://web\\.archive\\.org/",

  # FIXME: These URLs keep returning 404 errors, although they should be publicly
  # accessible.
  "^https?://github\\.com/ivmai/bdwgc/issues/133$",
  "^https?://github\\.com/ivmai/bdwgc/issues/225$",
]
