#############################  Cache  ###############################

# Enable link caching. This can be helpful to avoid checking the same links on
# multiple runs.
cache = true

# Discard all cached requests older than this duration.
max_cache_age = "7d"

#############################  Requests  ############################

exclude_path = [
  "_site",                             # build output
  "_sass/mixins/_link-with-icon.scss", # lists URL prefixes,
  "_data/packages.yaml",               # contains URL templates
  "_data/packages-nightly.yaml",       # contains URL templates
  "_data/bountysource.json",           # potentially obsolete URLs
  "_data/opencollective.json",         # potentially obsolete URLs
  "_data/others.json",                 # potentially obsolete URLs
  ".*\\.csv",                          # parser misreads URLs in CSV files
  "assets/community/contributors.svg", # pre-generated asset

  # contains templates with incomplete URLs
  "_plugins",
  "_layouts",
  "_includes",
  "_style_guide",
  "_pages/blog/authors.html",
  "_pages/blog/tags.md",
  "_pages/releases/feed.xml",
  "_pages/sitemap.md",
  "feed.xml",
  "index.md",
]

# Enable the checking of fragments in links.
include_fragments = "full"

# Root path to use when checking absolute local links, must be an absolute path
root_dir = "."
